#!/usr/bin/env python3
"""
kimi_review - Fetch Kimi AI-generated paper blog from papers.cool

Usage:
    python kimi_review.py <arxiv_id> [-o OUTPUT] [-l LANG]

Examples:
    python kimi_review.py 2602.10999
    python kimi_review.py 2602.10999 -o my_paper.md
    python kimi_review.py 2602.10999 -l en
"""

import argparse
import html
import re
import sys

import requests

API_URL = "https://papers.cool/arxiv/kimi"
PAPER_URL = "https://papers.cool/arxiv/{arxiv_id}"
ARXIV_URL = "https://arxiv.org/abs/{arxiv_id}"


def fetch_paper_title(arxiv_id: str) -> str:
    """Fetch paper title from papers.cool page."""
    try:
        resp = requests.get(PAPER_URL.format(arxiv_id=arxiv_id), timeout=15)
        resp.raise_for_status()
        match = re.search(r'<a[^>]*class="title-link[^"]*"[^>]*>(.+?)</a>', resp.text)
        if match:
            return html.unescape(match.group(1)).strip()
    except Exception:
        pass
    return ""


def fetch_kimi_blog(arxiv_id: str) -> str:
    """Fetch blog content from papers.cool Kimi API (HTML format)."""
    resp = requests.post(
        API_URL,
        params={"paper": arxiv_id},
        timeout=120,
    )
    resp.raise_for_status()

    if not resp.text.strip():
        raise RuntimeError(
            f"Kimi has not yet generated a blog for this paper.\n"
            f"Please visit {PAPER_URL.format(arxiv_id=arxiv_id)} and click the [Kimi] button to trigger generation, "
            f"then retry after it completes."
        )

    return resp.text


def html_to_markdown(raw_html: str) -> str:
    """Convert Kimi HTML output to clean Markdown."""
    text = raw_html

    # Convert Q&A headings to markdown headings
    text = re.sub(
        r'<p class="faq-q"><strong>(Q\d+)</strong>:\s*(.+?)</p>',
        r"## \1: \2",
        text,
    )

    # Remove faq-a div tags
    text = re.sub(r'<div class="faq-a">\s*', "", text)
    text = re.sub(r"\s*</div>", "", text)

    # Process <strong> -> **
    text = re.sub(r"<strong>(.+?)</strong>", r"**\1**", text)

    # Process <i> -> *
    text = re.sub(r"<i>(.+?)</i>", r"*\1*", text)

    # Process hyperlinks <a href="...">text</a> -> [text](url)
    text = re.sub(
        r'<a[^>]*href="([^"]*)"[^>]*>(.+?)</a>',
        r"[\2](\1)",
        text,
    )

    # Process <p> tags
    text = re.sub(r"<p[^>]*>", "", text)
    text = text.replace("</p>", "")

    # Remove remaining HTML tags (e.g. <sup>, <sub>, <i class="fa ...">)
    text = re.sub(r"</?sup>", "", text)
    text = re.sub(r"</?sub>", "", text)
    text = re.sub(r'<i class="fa[^"]*"></i>', "", text)
    text = re.sub(r"<hr[^>]*/?>", "---", text)

    # Decode HTML entities
    text = html.unescape(text)

    # Collapse excessive blank lines (keep at most two newlines)
    text = re.sub(r"\n{4,}", "\n\n\n", text)

    return text.strip()


def build_markdown(arxiv_id: str, title: str, blog_md: str) -> str:
    """Assemble final Markdown file content."""
    lines = []

    if title:
        lines.append(f"# {title}")
    else:
        lines.append(f"# arXiv: {arxiv_id}")

    lines.append("")
    lines.append(f"> Source: [papers.cool]({PAPER_URL.format(arxiv_id=arxiv_id)}) | "
                 f"[arXiv]({ARXIV_URL.format(arxiv_id=arxiv_id)})")
    lines.append(f"> Generated by Kimi AI")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(blog_md)
    lines.append("")

    return "\n".join(lines)


def normalize_arxiv_id(arxiv_id: str) -> str:
    """Strip version suffix from arXiv ID (e.g. v1, v2)."""
    return re.sub(r"v\d+$", "", arxiv_id.strip())


def main():
    parser = argparse.ArgumentParser(
        description="Fetch Kimi AI-generated paper blog from papers.cool and save as Markdown"
    )
    parser.add_argument("arxiv_id", help="arXiv paper ID, e.g. 2602.10999")
    parser.add_argument(
        "-o", "--output",
        help="Output filename (default: <arxiv_id>.md)",
    )
    args = parser.parse_args()

    arxiv_id = normalize_arxiv_id(args.arxiv_id)
    output = args.output or f"{arxiv_id}.md"

    print(f"Fetching paper info: {arxiv_id} ...")
    title = fetch_paper_title(arxiv_id)
    if title:
        print(f"Paper title: {title}")

    print(f"Fetching Kimi blog from papers.cool ...")
    try:
        raw_html = fetch_kimi_blog(arxiv_id)
    except requests.exceptions.HTTPError as e:
        print(f"Request failed: {e}", file=sys.stderr)
        sys.exit(1)
    except RuntimeError as e:
        print(str(e), file=sys.stderr)
        sys.exit(1)

    blog_md = html_to_markdown(raw_html)
    final_md = build_markdown(arxiv_id, title, blog_md)

    with open(output, "w", encoding="utf-8") as f:
        f.write(final_md)

    print(f"Saved to: {output}")


if __name__ == "__main__":
    main()
